#!/usr/bin/env fish

set -l json (niri msg --json workspaces-with-hidden)
set -l name (echo $json | jq -r '.[] | select(.is_focused) | .name // ""')
set -l id (echo $json | jq -r '.[] | select(.is_focused) | .id')

if test "$name" = stash
    niri-stash-leave
else
    echo $id >"$XDG_RUNTIME_DIR/niri-stash-prev"
    niri msg action focus-workspace stash
end
