# ~/.config/kitty/kitty.conf

# Shell
shell /usr/sbin/fish
login_shell yes

# Font
font_family JetBrainsMono Nerd Font
font_size 12

# Farger
background #1E1E2E
#background 282a36dd
foreground #CDD6F4
selection_background #575268
selection_foreground #1E1E2E
cursor #F5E0DC

# Oppførsel

enabled_layouts splits, stack, tall, grid
enable_audio_bell no
confirm_os_window_close 0
background_opacity 0.95
window_padding_width 0
scrollback_lines 5000
allow_remote_control yes
listen_on unix:@kitty

# Tastatursnarveier
map ctrl+shift+enter new_window
map ctrl+shift+w close_window
map ctrl+shift+h previous_tab
map ctrl+shift+l toggle_layout stack
map ctrl+shift+a focus_visible_window
map ctrl+shift+n next_layout
map ctrl+left  neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up    neighboring_window up

map ctrl+down  neighboring_window down
term xterm-256color
